export const ActionTypes={
  'MESSAGE_SOCKET_CONNECTION':'MESSAGE_SOCKET_CONNECTION',
  'MESSAGE_SOCKET_INCOMING_EVENT':'MESSAGE_SOCKET_INCOMING_EVENT',
  'MESSAGE_SOCKET_FAILURE':'MESSAGE_SOCKET_FAILURE',
  'DISCONNECT_SUCCESS':'DISCONNECT_SUCCESS'
};