export const ActionTypes = {
  'MESSAGE_SOCKET_CONNECTION': 'MESSAGE_SOCKET_CONNECTION',
  'MESSAGE_SOCKET_INCOMING_EVENT': 'MESSAGE_SOCKET_INCOMING_EVENT',
  'MESSAGE_SOCKET_FAILURE': 'MESSAGE_SOCKET_FAILURE',
  'DISCONNECT_SUCCESS': 'DISCONNECT_SUCCESS',
  'GET_EXCHANGES': 'GET_EXCHANGES',
  'GET_EXCHANGES_SUCCESS': 'GET_EXCHANGES_SUCCESS',
  'GET_EXCHANGES_FAILURE': 'GET_EXCHANGES_FAILURE',
  'GET_OBJECT_FROM_COMPONENT':'GET_OBJECT_FROM_COMPONENT',
  'GET_OBJECT_FROM_COMPONENT_SUCCESS':'GET_OBJECT_FROM_COMPONENT_SUCCESS',
  'GET_OBJECT_FROM_COMPONENT_FAILURE':'GET_OBJECT_FROM_COMPONENT_FAILURE'
};